// EXERCICIOS CAP 2

// EXERCICIO 1

SELECT DEPARTMENT_ID DEPTO_ID
FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID = 'ST_CLERK'
ORDER BY 1 DESC;


// EXERCICIO 2

SELECT COUNTRY_ID CO, COUNTRY_NAME
FROM COUNTRIES
minus
SELECT COUNTRY_ID CO, COUNTRY_NAME
FROM COUNTRIES 
NATURAL JOIN LOCATIONS
NATURAL JOIN DEPARTMENTS;


//EXERCICIO 3

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;


SELECT JOB_ID, DEPARTMENT_ID, 'A' DUMMY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10
UNION
SELECT DISTINCT JOB_ID, DEPARTMENT_ID, 'B' DUMMY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50
UNION
SELECT JOB_ID, DEPARTMENT_ID, 'C' DUMMY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20
order by DUMMY;


//EXERCICIO 4

SELECT EMPLOYEE_ID, JOB_ID FROM EMPLOYEES
INTERSECT 
SELECT EMPLOYEE_ID, JOB_ID FROM JOB_HISTORY;

//EXERCICIO 5

SELECT last_name,department_id,TO_CHAR(null)
FROM   employees
UNION
SELECT TO_CHAR(null),department_id,department_name
FROM  departments;


